
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsyqsgswdcrezdkraiak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzeXFzZ3N3ZGNyZXpka3JhaWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NzU3MzgsImV4cCI6MjA1ODE1MTczOH0.KKjD_7pfa-fdCTqjhXBU0EzGJ6q0tu_QkSDldZ9AjxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Disable session detection in URL to avoid email confirmation redirects
    storage: localStorage
  }
});
